### ISSUE TITLE
Cannot select Heltec T114 board in Arduino IDE

### ISSUE THREAD

**Issue by WJ4IoT** [HelTecAutomation/Heltec_nRF52#1]
My first observation is that the link to "Using Arduino IDE Boards Manager (preferred)" does not work
But I assume this is just add in the Arduino IDE - preferences:
https://resource.heltec.cn/download/package_heltec_esp32_index.json

However in the board overview I do not see (yet) the "Heltec T114".
Did I miss anything?

**Comment by Heltec-Aaron-Lee** [comment]
Please try this json file: https://resource.heltec.cn/download/package_heltec_nrf_index.json
